### ISSUE TITLE
/*CssUrlRewrite:skip*/ does not work on fonts

### ISSUE THREAD

**Issue by binarykitchen** [Jpunt/grunt-css-url-rewrite#1]
In one of my LESS files I have this:

``` css
@font-face {
    font-family: 'icons';
    src: url('/fonts/icons/i.eot'); /*CssUrlRewrite:skip*/
    src: url('/fonts/icons/i.eot?#iefix') format('embedded-opentype'),
         url('/fonts/icons/i.woff') format('woff'),
         url('/fonts/icons/i.ttf') format('truetype'),
         url('/fonts/icons/i.svg#icons') format('svg'); /*CssUrlRewrite:skip*/

    font-weight: normal;
    font-style: normal;
}
```

But your grunt task is not ignoring these lines. These icon fonts are still base64 encoded. A bug in your regex?
